
site_name: Pibiger 
site_url: https://wiki.pibiger-tech.com

nav :
- Home: index.md
- SavvyCAN Series:
  - SavvyCAN-FD-C: savvycan/savvycan-fd-c.md
  - SavvyCAN-FD-X2: savvycan/savvycan-fd-x2.md
- Raspberry PI:
  - PI-CAMV2: raspberry_pi/pi-camv2.md

theme:
  name: mkdocs

markdown_extentions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search

extra_css:
  - resources/css/extra.css

copyright: |
  &copy; 2023 <a href="https://www.pibiger-tech.com"  target="_blank" rel="noopener">Pibiger</a>